version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8000"
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - ENDPOINT_ID=${ENDPOINT_ID}
